version: '3.7'

services:
  frontend:
    container_name: progressciv-frontend-react
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 4000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true